# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:

    - name: OE setup | Run the install-windows-prereqs.ps1 script (this may take a while)
      script: ../install-windows-prereqs.ps1
        -InstallPath         "C:\oe_prereqs"
        -LaunchConfiguration "{{ launch_configuration }}"
        -DCAPClientType      "Azure"
        -InstallDocker

    - name: Check installed Intel PSW version
      ansible.windows.win_powershell:
        script: |
          (Get-WmiObject Win32_PnPSignedDriver | select DeviceName, DriverVersion, Manufacturer | where {$_.DeviceName -like "*Guard Extensions Platform*"}).DriverVersion
      register: intel_psw_version

    - name: Print Intel PSW version
      debug:
        var: intel_psw_version.output
    
    - name: Check installed Intel DCAP version
      ansible.windows.win_powershell:
        script: |
          (Get-Item C:\\Windows\\System32\\sgx_dcap_ql.dll).VersionInfo.ProductVersion
      register: intel_dcap_version

    - name: Print Intel DCAP version
      debug:
        var: intel_dcap_version.output

    # One way to ensure the system is reliable just after a reboot, is to set WinRM to a delayed startup
    - name: Ensure WinRM starts when the system has settled and is ready to work reliably
      win_service:
        name: WinRM
        start_mode: delayed

    - name: OE setup | Windows Updates
      block:
        - name: Install all security, critical, and rollup updates without a scheduled task
          win_updates:
            category_names:
              - SecurityUpdates
              - CriticalUpdates
              - UpdateRollups
            reboot: yes
            reboot_timeout: 3600
      always:
        - name: OE setup | Reboot the node
          win_reboot:

    - import_role:
        name: windows/openenclave
        tasks_from: validation.yml
